### PR TITLE
[HOPSWORKS-2046] kafka broker should use local zk if it exists

### PR DESCRIPTION
**Pull request by tkakantousis**

### CODE REVIEW

**Comment by tkakantousis** [comment]
Not sure it will fix the deployment issue, I thought this https://github.com/logicalclocks/kafka-cookbook/blob/master/Karamelfile#L8 meant all kafka::default on all nodes will wait on zookeeper::default on all nodes before starting, so all zookeeper instances should be up already

**Comment by SirOibaf** [comment]
Yes, but the issue is that while SystemD sees Zookeeper as running, the node hasn't yet joined the group so it's not ready to accept registrations from Kafka nodes. We should probably add a check in Zookeeper to wait until is healthy before marking the recipe as succeeded. If we do that, then it should be trivial to replace the IP here with the consul domain name.

**Comment by tkakantousis** [comment]
Ok I will try to have a look, don't merge yet, thanks.

**Comment by tkakantousis** [comment]
https://github.com/logicalclocks/kzookeeper/pull/17

**Review by SirOibaf — APPROVED** [review]

**Pull request merged**
